language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: hhvm

install: travis_retry composer install --no-interaction --prefer-source

script: make test
