language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: hhvm

install:
  - if [[ ${TRAVIS_PHP_VERSION:0:5} == "5.5.9" ]]; then travis_retry composer require laravel/framework; fi
  - travis_retry composer install --no-interaction --prefer-source

script: make test

