language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: hhvm

install:
  - travis_retry composer update --no-interaction --prefer-source

script: make test

